language: python
python:
  - 2.6
  - 2.7
install:
  - pip install -r requirements/dev.txt
  - pip install .
  - pip install Django==$DJANGO_VERSION
env:
  - DJANGO_VERSION=1.6.2
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.3.7
script: python -m armstrong.dev.dev_django test
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#armstrongcms"
