language: python
python:
  - 2.6
  - 2.7
install:
  - pip install -r requirements/dev.txt
  - if [[ $DJANGO_VERSION == '1.3.7' ]]; then pip install "django-mptt>=0.5.5,<0.6" "django-model-utils>=1.0.0,<1.4"; else pip install "django-model-utils>=1.0.0"; fi
  - pip install .
  - pip install coverage coveralls Django==$DJANGO_VERSION
env:
  - DJANGO_VERSION=1.7.1
  - DJANGO_VERSION=1.6.8
  - DJANGO_VERSION=1.5.11
  - DJANGO_VERSION=1.4.16
  - DJANGO_VERSION=1.3.7
script: coverage run -m armstrong.dev.dev_django test
after_success: coveralls
matrix:
  exclude:
    - python: 2.6
      env: DJANGO_VERSION=1.7.1
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#armstrongcms"
